### DISCUSSION TITLE
发现大问题！！！

### DISCUSSION THREAD

**Discussion by Yuumi0221** [YunYouJun/hexo-theme-starry#218] [Q&A 疑难杂症] [answered]
我正在学网安的朋友发现搜索框存在 [XSS 注入漏洞](https://www.freebuf.com/vuls/280992.html)！！具体如下图：
![tmp4267](https://user-images.githubusercontent.com/59047663/146679268-5f83fa5e-faa1-4993-b136-c7721da2c586.png)
虽然github好像不能跨域，但是可以看到回显。
以防万一被攻击（这个太明显了），是否考虑给搜索框做字符过滤？
或者像我一样直接把回显给删除：`Hexo根目录\themes\yun\languages\zh-CN.yml`（以及其他语言）中：
```YAML
search:
  placeholder: 搜索...
  empty: "找不到您查询的内容"    #删除后面的${ }
  hits: "找到 ${hits} 条结果"
  hits_time: "找到 ${hits} 条结果（用时 ${time} 毫秒）"
```
![tmp66B5](https://user-images.githubusercontent.com/59047663/146679433-4dfe151d-bd6c-4f64-be26-ac1c53748521.png)
---
（顺带一提，朋友正疯狂尝试各种寻找网站漏洞，真可怕啊orz）
