### DISCUSSION TITLE
改变footer日期语言

### DISCUSSION THREAD

**Discussion by emerisly** [YunYouJun/hexo-theme-starry#222] [Q&A 疑难杂症] [answered]
请问网站的footer中的日期，比如“本博客已萌萌哒地运行 xx天 xx 小时 x  分 xx 秒(●'◡'●)” 中的中文如何能切换成英文？已经把config的language设置为English了，也没有在time format中找到具体切换语言的setting
看了很多示例网站都没有找到改过这个语言的，请问有办法把时间改成其他语言吗，比如 "xx days xx hours xx minutes xx seconds"
感谢！

**Comment by YunYouJun** [comment, marked as answer]
Hello，此部分内容为自定义。

在 `yun.yml` 中配置：

```yml
footer:
  live_time:
    enable: false
    prefix: 本博客已萌萌哒地运行
    suffix: (●'◡'●)
    start_time: "2019-04-12T00:00:00"
```

部分即可。
