### DISCUSSION TITLE
waline，前段怎么更新啊，前后版本差的太多了，

### DISCUSSION THREAD

**Discussion by weaving-dreams** [YunYouJun/hexo-theme-starry#290] [Q&A 疑难杂症] [answered]
waline，前段怎么更新啊，前后版本差的太多了，

**Comment by YunYouJun** [comment]
In theory, waline's CDN should always be up to date. What do you want to update?

**Comment by weaving-dreams** [comment]
![image](https://user-images.githubusercontent.com/100774247/167969559-cc0dac7a-5f78-43fd-855a-d1ee1d7d3cc7.png)
waline这个评论区都到2.4.1了，博客评论区的还在1.6.0，怎么给他更新一下啊

**Comment by YunYouJun** [comment, marked as answer]
已升级 Waline 至 `v2`，Released in `v1.9.1`。
此外可以通过覆盖 `_config.yun.yml` `vendors` 的方式，自主控制版本：

```yml
vendors:
  waline:
    css: # Waline 不同版本的 CDN，见官方文档
    js: # Waline 不同版本的 CDN，见官方文档
```
