### DISCUSSION TITLE
sidebar图片设置后位于上方

### DISCUSSION THREAD

**Discussion by myp0402** [YunYouJun/hexo-theme-starry#309] [Q&A 疑难杂症] [answered]
在config.yun.yml中设置了侧边栏背景
```YAML
sidebar:
  bg_image: https://s3.bmp.ovh/imgs/2022/06/02/c25cb108a5f234b5.jpg
  bg_position: bottom 1rem centersss
  tagcloud:
    enable: false
    amount: 20
```
然而，当我hexo s的时候。。。
![截屏2022-06-02 11.11.37.png](https://pic.rmb.bdstatic.com/bjh/025ac3ef90c13073164bd6fbe48491c7.png)
就是这样，Orz
