### DISCUSSION TITLE
有没有办法单独更改一言的颜色

### DISCUSSION THREAD

**Discussion by myp0402** [YunYouJun/hexo-theme-starry#310] [Q&A 疑难杂症] [answered]
如题，如果var.styl改会导致左侧图标的颜色也变成一样的。

**Comment by YunYouJun** [comment, marked as answer]
```css
#say-content {
  color: xxx;
}
```
