### DISCUSSION TITLE
请问 RSS 在 Google 浏览器下乱码如何解决？

### DISCUSSION THREAD

**Discussion by guowei-gong** [YunYouJun/hexo-theme-starry#324] [Q&A 疑难杂症]
版本信息：
Yun: 1.10.4
hexo: 6.2.0
hexo-cli: 4.3.0
os: darwin 20.6.0 11.6.2

我的 config.yml 与 config.yun.yml 关于 rss 的配置如下：
config.yml
```
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '
  order_by: -updated
  icon: favicon.png
  autodiscovery: true
  template:
```

config.yun.yml
```
  - name: RSS
    link: /atom.xml # config.feed.path
    icon: ri:rss-line
    color: orange
```

访问 localhost:4000/atom.xml 如下：
![image](https://user-images.githubusercontent.com/62499904/178642687-67ba12f8-8816-4f3b-bc40-9d0d26eff858.png)
