### DISCUSSION TITLE
PUG 语法基础问题 求帮助

### DISCUSSION THREAD

**Discussion by wgx-dh** [YunYouJun/hexo-theme-starry#363] [Q&A 疑难杂症] [answered]
我想使用 umami 做网站监控 
（需要在 <head> 中引入 js）

我修改了以下几个步骤：

1. 修改 主题的配置文件 加入
```yml
umami:
  data-website-id: e4d6*************420cc10b4
  js-url: https://*************/umami.js
```

2. 修改 layout/_partial/head.pug 加入
```
if theme.umami
  script(async, defer, data-website-id= "" + theme.umami.data-website-id, src= "" + theme.umami.js-url)
```

渲染出来的是 null
![image](https://user-images.githubusercontent.com/63238251/197440599-a7318e42-63fb-4155-8c5a-165e1475458a.png)

这个 script 标签应该怎么写啊  我照猫画虎尝试了很多写法都不行 求热心大佬解答
