### DISCUSSION TITLE
Demo Sites | 示例站点

### DISCUSSION THREAD

**Discussion by YunYouJun** [YunYouJun/hexo-theme-starry#97] [Show 分享展示]
> From https://github.com/YunYouJun/hexo-theme-yun/issues/3

欢迎在此处分享展示您使用本主题搭建的最终站点！您的站点将可能被选为示例站点，并展示于主题文档中。

**您可以选择 `Show 向大家展示` 这一分类并新建一个 `discussion`，而不必在此帖下回复。**

---

### 现在示例站点已采用自助模式

您可以直接为 [docs/.vuepress/assets/sites.json](https://github.com/YunYouJun/hexo-theme-yun/blob/dev/docs/.vuepress/assets/sites.json) 文件创建 PR，以将您的站点作为示例站点。

> 我将不再手动添加本页面留言的示例站点。

---

## 格式

请尽可能遵循如下格式：

[云游君的小站](https://www.yunyoujun.cn)

```yaml
name: 云游君的小站 # 最好不要太长，控制在八个中文字符宽度内
url: https://www.yunyoujun.cn
avatar: avatar.jpg # 你的头像链接，请确保它为正方形或圆形。
desc: # 简单描述一下你的站点、或者你喜欢的句子
```

其他你想要说的话（畅所欲言～）

---

那么向大家展示你的站点吧～

[示例站点 | 使用文档](https://yun.yunyoujun.cn/demo/)
