### ISSUE TITLE
[Usage Problem]貌似fastly.jsdelivr现在也比较不稳定了

### ISSUE THREAD

**Issue by Poteato0** [YunYouJun/hexo-theme-starry#314]
今天听hexo群友们说fastly.jsdelivr也不稳定了，然后去测试了一下，报了很多超时
在此之前本站十分流畅且无报错，现在会卡很久，并附带很多超时报错
云游认为是否需要更换cdn，应该算影响了正常使用了，求修复QAQ
![](https://s2.loli.net/2022/06/08/fEgivUTK26YeaMZ.png)

**Comment by YunYouJun** [comment]
可以通过 `_config.yun.yml` 自定义 vendors：

```yml
vendors:
  # 以 '/' 结尾
  host: 'https://fastly.jsdelivr.net/npm/'
```

我现在也不确定哪个 CDN 能继续使用……
