### ISSUE TITLE
[Bug Report]文档中关于代码高亮的功能部分已经过时

### ISSUE THREAD

**Issue by Chengzi600** [YunYouJun/hexo-theme-starry#389]
https://yun.yunyoujun.cn/guide/config.html
文档中关于代码高亮显示的配置文件，给出的如下配置文件过时
``` yaml
# 关闭 highlight
highlight:
  enable: false
# 启用 prism
prismjs:
  enable: true
  preprocess: true
  line_number: false
  tab_replace: ''
```

参见如下官方文档(https://hexo.io/zh-cn/docs/syntax-highlight) 中给出的v7.0以上默认配置
 渲染器的切换由`syntax_highlighter`决定

> PrismJS 默认禁用。启用 PrismJS 前应设置 `highlight.enable` 为 `false`（v7.0.0以下）或设置 `syntax_highlighter` 为 `prismjs`（v7.0.0及以上）
``` yaml
# _config.yml
syntax_highlighter: prismjs
prismjs:
  preprocess: true
  line_number: true
  line_threshold: 0
  tab_replace: ''
```

并且，根据官方文档教程切换prismjs后，代码高亮仍然无法正常工作
希望尽快查看这个问题，感谢！
