### ISSUE TITLE
[Usage Problem]请问markdown的 >引用 怎么更改颜色

### ISSUE THREAD

**Issue by Poteato0** [YunYouJun/hexo-theme-starry#391]
如题，我想让markdown的`> 引用`渲染成橙色，默认的是蓝色(如下)，我翻查了配置文档但好像没有类似的配置
![image](https://github.com/YunYouJun/hexo-theme-yun/assets/99303427/9054949a-40d0-4556-900b-f93515b1bd24)

我知道可以使用`<div class="warning"></div>`包裹这段引用，但我文章中的引用太多了，请问有没有简易的方式，让普通的引用变成那样的橙色，或者默认就被`<div class="warning"></div>`包裹？
![image](https://github.com/YunYouJun/hexo-theme-yun/assets/99303427/fb6db303-f93e-4476-8d24-2f3c301d808a)

**Comment by YunYouJun** [comment]
直接覆盖 CSS 样式即可。

新建 `styles/index.scss`。

```css
:root {
  --smc-border-color: red;
}
```

**Comment by YunYouJun** [comment]
或覆盖 class 样式：

```css
.markdown-body blockquote {
  border-left-color: black;
}
```
